# Generated by Django 4.0.4 on 2025-04-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_mobile', '0006_mobileassignment_certifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileassignment',
            name='certifications',
        ),
    ]
