# Generated by Django 4.0.4 on 2025-06-16 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_profile', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('administration_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_administration_level', to='v1_profile.levels')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='RoleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_access', models.IntegerField(choices=[(1, 'Read'), (2, 'Approve'), (3, 'Submit'), (4, 'Edit'), (5, 'Delete')], default=1)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_role_access', to='v1_profile.role')),
            ],
            options={
                'db_table': 'role_access',
                'unique_together': {('role', 'data_access')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_administration', to='v1_profile.administration')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_user_role', to='v1_profile.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_role',
                'unique_together': {('user', 'role', 'administration')},
            },
        ),
        migrations.DeleteModel(
            name='Access',
        ),
    ]
