# Generated by Django 4.0.4 on 2025-04-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_profile', '0015_alter_entitydata_administration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='role',
            field=models.IntegerField(choices=[(1, 'Super Admin'), (2, 'Admin')]),
        ),
    ]
