# Generated by Django 4.0.4 on 2025-06-16 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapprovalassignment',
            name='administration',
        ),
        migrations.RemoveField(
            model_name='formapprovalassignment',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formapprovalassignment',
            name='user',
        ),
        migrations.DeleteModel(
            name='FormAccess',
        ),
        migrations.DeleteModel(
            name='FormApprovalAssignment',
        ),
    ]
