# Generated by Django 4.0.4 on 2025-04-11 08:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0038_alter_questions_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='submission_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Registration'), (2, 'Monitoring')]), blank=True, default=list, size=None),
        ),
    ]
