# Generated by Django 4.0.4 on 2025-04-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0039_alter_forms_submission_types'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewJmpCriteria',
        ),
    ]
