# Generated by Django 4.0.4 on 2025-04-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0040_delete_viewjmpcriteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formcertificationassignment',
            name='administrations',
        ),
        migrations.RemoveField(
            model_name='formcertificationassignment',
            name='assignee',
        ),
        migrations.DeleteModel(
            name='FormCertificationAdministration',
        ),
        migrations.DeleteModel(
            name='FormCertificationAssignment',
        ),
    ]
