# Generated by Django 4.0.4 on 2025-04-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0041_remove_formcertificationassignment_administrations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFormAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.IntegerField(choices=[(1, 'Read'), (2, 'Editor'), (3, 'Approver')])),
                ('user_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_form_access', to='v1_forms.userforms')),
            ],
            options={
                'db_table': 'user_form_access',
            },
        ),
    ]
