# Generated by Django 4.0.4 on 2025-04-27 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0041_remove_formcertificationassignment_administrations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.IntegerField(choices=[(1, 'Read'), (2, 'Edit'), (3, 'Approve')])),
                ('user_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_form_access', to='v1_forms.userforms')),
            ],
            options={
                'db_table': 'user_form_access',
            },
        ),
    ]
