# Generated by Django 4.0.4 on 2025-04-28 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0042_formaccess'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW IF EXISTS data_category;
            DROP MATERIALIZED VIEW IF EXISTS view_jmp_count;
            DROP MATERIALIZED VIEW IF EXISTS view_jmp_data;
            DROP MATERIALIZED VIEW IF EXISTS view_data_options;
            DROP MATERIALIZED VIEW IF EXISTS view_jmp_criteria;
            DROP MATERIALIZED VIEW IF EXISTS view_options;
            """
        )
    ]
