# Generated by Django 4.0.4 on 2025-04-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0043_remove_all_materialize_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='type',
        ),
    ]
