# Generated by Django 4.0.4 on 2025-06-17 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1_data', '0001_initial'),
        ('v1_profile', '0003_role_roleaccess_userrole_delete_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_forms', '0003_remove_formapprovalassignment_administration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('uuid', models.UUIDField(default=None, null=True)),
                ('file', models.URLField(default=None, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=None, null=True)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_data_batch', to='v1_profile.administration')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_batch_data', to='v1_forms.forms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data_batch', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batch',
            },
        ),
        migrations.CreateModel(
            name='DataBatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_data_list', to='v1_approval.databatch')),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_batch_list', to='v1_data.formdata')),
            ],
            options={
                'db_table': 'batch_data',
            },
        ),
        migrations.CreateModel(
            name='DataBatchComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_batch_comment', to='v1_approval.databatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_batch_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batch_comment',
            },
        ),
        migrations.CreateModel(
            name='DataBatchAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_batch_attachment', to='v1_approval.databatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_batch_attachment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batch_attachment',
            },
        ),
        migrations.CreateModel(
            name='DataApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=None, null=True)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_data_approval', to='v1_profile.administration')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_approval', to='v1_approval.databatch')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_data_approval', to='v1_profile.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_approval_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_approval',
            },
        ),
    ]
