# Generated by Django 4.0.4 on 2025-06-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_approval', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databatchattachments',
            old_name='file',
            new_name='file_path',
        ),
        migrations.RemoveField(
            model_name='databatchattachments',
            name='user',
        ),
        migrations.AddField(
            model_name='databatchattachments',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='databatchcomments',
            name='file_path',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
