# Generated by Django 4.0.4 on 2025-05-30 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1_data', '0001_initial'),
        ('v1_forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingdatabatchcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_batch_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingdatabatch',
            name='administration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_pending_data_batch', to='v1_profile.administration'),
        ),
        migrations.AddField(
            model_name='pendingdatabatch',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_batch_data', to='v1_forms.forms'),
        ),
        migrations.AddField(
            model_name='pendingdatabatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pending_data_batch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingdataapproval',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_approval', to='v1_data.pendingdatabatch'),
        ),
        migrations.AddField(
            model_name='pendingdataapproval',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_assigned_pending_data', to='v1_profile.levels'),
        ),
        migrations.AddField(
            model_name='pendingdataapproval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assigned_pending_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formdata',
            name='administration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_form_data', to='v1_profile.administration'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='batch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_form_data', to='v1_data.pendingdatabatch'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_data_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formdata',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_form_data', to='v1_forms.forms'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='v1_data.formdata'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answers',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answers',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_answer', to='v1_data.formdata'),
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='v1_forms.questions'),
        ),
        migrations.AddField(
            model_name='answerhistory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_history_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerhistory',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_answer_history', to='v1_data.formdata'),
        ),
        migrations.AddField(
            model_name='answerhistory',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_history', to='v1_forms.questions'),
        ),
    ]
