# Generated by Django 4.0.4 on 2025-05-29 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0004_create_view_pending_data_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinganswers',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pendinganswers',
            name='pending_data',
        ),
        migrations.RemoveField(
            model_name='pendinganswers',
            name='question',
        ),
        migrations.RemoveField(
            model_name='pendingformdata',
            name='administration',
        ),
        migrations.RemoveField(
            model_name='pendingformdata',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='pendingformdata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pendingformdata',
            name='data',
        ),
        migrations.RemoveField(
            model_name='pendingformdata',
            name='form',
        ),
        migrations.RemoveField(
            model_name='pendingformdata',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='answers',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formdata',
            name='batch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_form_data', to='v1_data.pendingdatabatch'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formdata',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formdata',
            name='submitter',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PendingAnswerHistory',
        ),
        migrations.DeleteModel(
            name='PendingAnswers',
        ),
        migrations.DeleteModel(
            name='PendingFormData',
        ),
    ]
