# Generated by Django 4.0.4 on 2025-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0033_assign_submission_type_to_previous_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='submission_type',
            field=models.IntegerField(choices=[(1, 'Registration'), (2, 'Monitoring')], default=1),
        ),
        migrations.AlterField(
            model_name='pendingformdata',
            name='submission_type',
            field=models.IntegerField(choices=[(1, 'Registration'), (2, 'Monitoring')], default=1),
        ),
    ]
