# Generated by Django 4.0.4 on 2025-04-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0034_alter_formdata_submission_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewDataOptions',
        ),
        migrations.DeleteModel(
            name='ViewJMPCount',
        ),
        migrations.DeleteModel(
            name='ViewJMPData',
        ),
        migrations.DeleteModel(
            name='ViewOptions',
        ),
    ]
